// export const routes = [
//   {
//     path: "/",
//     label: "Dashboard",
//     icon: "Home",
//     showInSidebar: false,
//     order: 0,
//   },
//   {
//     path: "/logs",
//     label: "Logs",
//     icon: "ClipboardList", 
//     showInSidebar: true,
//     group: "Lead Management",
//     groupOrder: 1, 
//     order: 2,
//   },
//   {
//     path: "/business-loans",
//     label: "Business Loans",
//     icon: "ClipboardList", 
//     showInSidebar: true,
//     group: "Lead Management",
//     groupOrder: 1, 
//     order: 2,
//   },
//   {
//     path: "/mv-ivr-logs",
//     label: "MV IVR Logs",
//     icon: "ClipboardList", 
//     showInSidebar: true,
//     group: "Lead Management",
//     groupOrder: 1, 
//     order: 3,
//   },
//   {
//     path: "/cr-zype-success-leads",
//     label: "CR Zype success Leads",
//     icon: "ClipboardList", 
//     showInSidebar: true,
//     group: "Lead Management",
//     groupOrder: 1, 
//     order: 4,
//   }
// ];


// src/routes/routes.js
export const routes = [
  {
    path: "/",
    label: "Dashboard",
    icon: "Home",
    showInSidebar: false,
    order: 0,
    roles: ["admin", "super-admin", "kb-admin", "kb-mumbai", "kb-banglore", "mv-admin", "management"],
  },
  // Standalone module (no group) — call-center feedback: funnel + agent activity +
  // records, all under one entry (two tabs inside) so the sidebar stays uncluttered.
  {
    path: "/call-center-feedback",
    label: "Call-Center Feedback",
    icon: "MessageSquare",
    showInSidebar: true,
    order: 0.5,
    // Call-center agents see it too, but the page self-scopes to their OWN data.
    roles: ["super-admin", "mv-page-admin", "management"],
  },
  {
    path: "/logs",
    label: "Logs",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "Lead Management",
    groupOrder: 1,
    order: 2,
    roles: ["mv-admin"],
  },
  {
    path: "/business-loans",
    label: "Business Loans",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "Lead Management",
    groupOrder: 1,
    order: 3,
    roles: ["dev"],
  },
  {
    path: "/mv-ivr-logs",
    label: "MV IVR Logs",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "Lead Management",
    groupOrder: 1,
    order: 4,
    roles: ["admin", "dev"],
  },
  {
    path: "/cr-zype-success-leads",
    label: "CR Zype Success Leads",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "Lead Management",
    groupOrder: 1,
    order: 5,
    roles: ["dev"],
  },
  {
    path: "/kb-success-leads",
    label: "KB Logs",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "Lead Management",
    groupOrder: 1,
    order: 6,
    roles: ["dev", "kb-admin"],
  },
  // {
  //   path: "/kb-mumbai-success-leads",
  //   label: "KB Logs - Mumbai",
  //   icon: "ClipboardList",
  //   showInSidebar: true,
  //   group: "Lead Management",
  //   groupOrder: 1,
  //   order: 7,
  //   roles: ["super-admin", "kb-mumbai"],
  // },
  // {
  //   path: "/kb-banglore-success-leads",
  //   label: "KB Logs - Banglore",
  //   icon: "ClipboardList",
  //   showInSidebar: true,
  //   group: "Lead Management",
  //   groupOrder: 1,
  //   order: 8,
  //   roles: ["super-admin", "kb-banglore"],
  // },
 {
    // Cross-lender rollup — sits above the per-lender pages since it's the
    // entry point you scan before drilling into a single lender.
    path: "/all-lenders",
    label: "All Lenders",
    icon: "Building2",
    showInSidebar: true,
    group: "Lenders",
    groupOrder: 3,
    order: 19,
    roles: ["super-admin", "kb-admin", "mv-admin", "mv-page", "mv-page-admin", "management"],
  },
  {
    path: "/kb-lending-page",
    label: "KB Success Leads",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "Lenders",
    groupOrder: 3,
    order: 20,
    roles: ["super-admin", "kb-admin", "mv-page", "mv-page-admin", "management"],
  },
  {
    path: "/mv-success-leads",
    label: "MV Success Leads",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "Lenders",
    groupOrder: 3,
    order: 20,
    roles: ["super-admin", "mv-admin", "mv-page", "mv-page-admin", "management"],
  },
  {
    path: "/sc-response-leads",
    label: "SC Response Leads",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "Lenders",
    groupOrder: 3,
    order: 20,
    roles: ["super-admin", "mv-admin", "mv-page", "mv-page-admin", "management"],
  },
  {
    path: "/vivifi-webhook-leads",
    label: "Vivifi Webhook Leads",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "Lenders",
    groupOrder: 3,
    order: 21,
    roles: ["super-admin", "mv-page-admin", "management", "dev"],
  },
  {
    path: "/upswing-webhook",
    label: "UpSwing",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "Lenders",
    groupOrder: 3,
    order: 22,
    roles: ["super-admin", "mv-page-admin", "management", "dev"],
  },
  {
    path: "/upswing-funnel",
    label: "UpSwing Funnel",
    icon: "TrendingDown",
    showInSidebar: true,
    group: "Lenders",
    groupOrder: 3,
    order: 22.5,
    roles: ["super-admin", "mv-page-admin", "management", "dev"],
  },
  {
    path: "/apollo-webhook",
    label: "Apollo",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "Lenders",
    groupOrder: 3,
    order: 22.6,
    roles: ["super-admin", "mv-page-admin", "management", "dev"],
  },
  {
    path: "/apollo-funnel",
    label: "Apollo Funnel",
    icon: "TrendingDown",
    showInSidebar: true,
    group: "Lenders",
    groupOrder: 3,
    order: 22.7,
    roles: ["super-admin", "mv-page-admin", "management", "dev"],
  },
  {
    path: "/offer-leads-analytics",
    label: "High Analytics Dashboard",
    icon: "Home",
    showInSidebar: true,
    group: "High Ticket",
    groupOrder: 1.5,
    order: 8.5,
    roles: ["super-admin", "mv-page-admin", "management", "marketing"],
  },
  {
    path: "/disbursal-dashboard",
    label: "Disbursal Dashboard",
    icon: "TrendingUp",
    showInSidebar: true,
    group: "High Ticket",
    groupOrder: 1.5,
    order: 8,
    roles: ["super-admin", "mv-page-admin", "management"],
  },
  {
    path: "/offer-leads",
    label: "High Offer Leads",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "High Ticket",
    groupOrder: 1.5,
    order: 9,
    roles: ["super-admin", "mv-page", "mv-page-admin", "management", "marketing", "call-center", "call-center-40-65", "call-center-65plus"],
  },
  {
    path: "/selected-lenders",
    label: "High Selected Lenders",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "High Ticket",
    groupOrder: 1.5,
    order: 10,
    roles: ["super-admin", "mv-page", "mv-page-admin", "management", "marketing"],
  },
  {
    path: "/high-mis-funnel",
    label: "High MIS Funnel",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "High Ticket",
    groupOrder: 1.5,
    order: 10.5,
    roles: ["super-admin", "mv-page", "mv-page-admin", "management"],
  },
  {
    path: "/draft-leads-new",
    label: "High Draft Leads",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "High Ticket",
    groupOrder: 1.5,
    order: 12,
    roles: ["super-admin", "mv-page", "mv-page-admin", "management", "marketing"],
  },
  {
    path: "/short-offer-leads-analytics",
    label: "Short Analytics Dashboard",
    icon: "Home",
    showInSidebar: true,
    group: "Short Ticket",
    groupOrder: 2,
    order: 19,
    roles: ["super-admin", "short-page-admin", "management"],
  },
  {
    path: "/short-disbursal-dashboard",
    label: "Disbursal Dashboard",
    icon: "TrendingUp",
    showInSidebar: true,
    group: "Short Ticket",
    groupOrder: 2,
    order: 19.5,
    roles: ["super-admin", "short-page-admin", "management"],
  },
  {
    path: "/short-offer-leads",
    label: "Short Offer Leads",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "Short Ticket",
    groupOrder: 2,
    order: 20,
    roles: ["super-admin", "short-page-admin", "management", "call-center", "call-center-40-65", "call-center-65plus","marketing"],
  },
  {
    path: "/short-selected-lenders",
    label: "Short Selected Lenders",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "Short Ticket",
    groupOrder: 2,
    order: 21,
    roles: ["super-admin", "short-page-admin", "management", "marketing"],
  },
  {
    path: "/short-draft-leads",
    label: "Short Draft Leads",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "Short Ticket",
    groupOrder: 2,
    order: 22,
    roles: ["super-admin", "short-page-admin", "management", "marketing"],
  },
  {
    path: "/short-user-track",
    label: "Short User Track",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "Short Ticket",
    groupOrder: 2,
    order: 23,
    roles: ["super-admin", "short-page-admin", "management", "marketing"],
  },
  {
    path: "/cready-rpm",
    label: "Cready RPM",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "Short Ticket",
    groupOrder: 2,
    order: 24,
    roles: ["super-admin", "short-page-admin", "management", "marketing", "campaign-team"],
  },
  // Campaign Team — replica of Cready RPM with its own role + sidebar group.
  {
    path: "/campaign",
    label: "Campaign",
    icon: "Megaphone",
    showInSidebar: true,
    group: "Campaign",
    groupOrder: 2.5,
    order: 25,
    roles: ["super-admin", "campaign-team"],
  },
  // {
  //   path: "/short-kb-lending-page",
  //   label: "Short KB Success Leads",
  //   icon: "ClipboardList",
  //   showInSidebar: true,
  //   group: "Short Ticket",
  //   groupOrder: 2,
  //   order: 24,
  //   roles: ["super-admin", "kb-admin", "short-page-admin", "management"],
  // },
  // {
  //   path: "/lending-user-journey",
  //   label: "Lending User Journey",
  //   icon: "ClipboardList",
  //   showInSidebar: true,
  //   group: "Lead Management",
  //   groupOrder: 1,
  //   order: 13,
  //   roles: ["super-admin", "mv-page", "mv-page-admin", "mv-admin"],
  // },
  {
    path: "/user-track",
    label: "High User Track",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "High Ticket",
    groupOrder: 1.5,
    order: 14,
    roles: ["super-admin", "mv-page", "mv-page-admin", "mv-admin", "management", "marketing"],
  },
  // Intelligence — one standalone tab holding four modules (High Ticket, Short
  // Ticket, Campaigns, Lenders), switched in-page rather than duplicated into four
  // sidebar entries. Self-contained: it reads only, and shares no state with any
  // other module.
  //
  // super-admin only while the numbers are being validated. The data-quality gates
  // it surfaces (MIS coverage, missing approval signal) should be understood before
  // this is widened to management/marketing.
  //
  // ORDER: the sidebar sorts standalone entries and groups together in one list,
  // comparing a standalone's `order` against a group's `groupOrder`. 3.5 places
  // this immediately after the Lenders group (3) and before Security (4).
  {
    path: "/intelligence",
    label: "Intelligence",
    icon: "Brain",
    showInSidebar: true,
    order: 3.5,
    roles: ["super-admin"],
  },
  // Security was groupOrder 3 — the same value as Lenders — so the two only
  // separated by insertion order. Making it 4 is a no-op for what renders today
  // (Lenders already came first) and gives Intelligence a slot between them.
  {
    path: "/otp-logs",
    label: "OTP Logs",
    icon: "ShieldCheck",
    showInSidebar: true,
    group: "Security",
    groupOrder: 4,
    order: 30,
    roles: ["super-admin"],
  },
  {
    path: "/export-audit-logs",
    label: "Export Logs",
    icon: "FileDown",
    showInSidebar: true,
    group: "Security",
    groupOrder: 4,
    order: 31,
    roles: ["super-admin"],
  },
];